Q1.
empiler() peut renvoyer une exception car une fonction à l'intérieur peut en envoyer une.
